DROP TABLE IF EXISTS ShowToGenre CASCADE;
DROP TABLE IF EXISTS EpisodeToUser CASCADE;
DROP TABLE IF EXISTS Episodes CASCADE;
DROP TABLE IF EXISTS Season CASCADE;
DROP TABLE IF EXISTS Genre CASCADE;
DROP TABLE IF EXISTS Shows CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
